version: '2'

service : 
    im_service:
       build:
           content: 'server'
        volumes: 
           - ./code: $GOPATH/src/github.com/GoBelieveIO
    db:
      image: mysql
      ports:
       - "3306:3306"
      volumes:
       - ./db:/var/lib/mysql
       - ./conf:/var/
      networks:
        - web-db
    redis:
      image:redis
      ports:
        - "6379:6379"
      networks:
        - web-redis

networks:

   web-db:
     driver: bridge

   web-redis:
     driver: bridge
