version: '2'

services :
    im_service:
       build:
          context: Server/
       volumes:
          - ./Server/im_service:/go/src/GoBelieveIO
    db:
      image: mysql
      ports:
       - "3336:3306"
      volumes:
          - ./db:/var/lib/mysql
          - ./conf:/var/
      networks:
          - web-db
    redis:
      image: redis
      ports:
          - "6679:6379"
      networks:
          - web-redis

networks:

   web-db:
     driver: bridge

   web-redis:
     driver: bridge
